//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Company_Details
    {
        public int Id { get; set; }
        public string Benefit { get; set; }
        public string Co_Pay { get; set; }
        public string Room_Rent { get; set; }
        public string Day_Care_Treatment { get; set; }
        public string Restoration_Benefit { get; set; }
        public string Pre_Hospitalization { get; set; }
        public string Post_Hospitalization { get; set; }
        public string Ambulance_Charges { get; set; }
        public string Company_Id { get; set; }
        public string Company_Plan { get; set; }
        public string Status { get; set; }
    }
}
