//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comparision_Health_tbl
    {
        public int Id { get; set; }
        public string Benefit { get; set; }
        public string Co_Pay { get; set; }
        public string Room_Rent { get; set; }
        public string OPD { get; set; }
        public string Day_Care_Treatment { get; set; }
        public string Medical_Checkup { get; set; }
        public string Pre_Existing_Disease_Covered_After { get; set; }
        public string Domicilliary_Expenses { get; set; }
        public string Organ_Donar_Expenses { get; set; }
        public string Hospital_Cash_Daily_Limit { get; set; }
        public string Maternity_Benefit { get; set; }
        public string New_Born_Baby { get; set; }
        public string Pre_Hospitalization { get; set; }
        public string Post_Hospitalization { get; set; }
        public string Ambulance_Charges { get; set; }
        public string Health_Check_Up { get; set; }
        public string Restoration_Benefit { get; set; }
        public string Free_Look_Period { get; set; }
        public string Company_Id { get; set; }
        public string Company_Plan { get; set; }
        public string Status { get; set; }
    }
}
