//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Insurance_Record_Saved
    {
        public int ID { get; set; }
        public string Gender { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string City { get; set; }
        public string Income { get; set; }
        public string Self { get; set; }
        public string Adult { get; set; }
        public string Child { get; set; }
        public string Self_Age { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ServiceTax { get; set; }
        public string spouce_Age { get; set; }
        public string child1_Age { get; set; }
        public string child2_Age { get; set; }
        public Nullable<long> tid { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
