//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class healthRelation
    {
        public int Id { get; set; }
        public string AssigneeRelationshipName { get; set; }
        public string AssigneeRelationshipId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string InsuranceType { get; set; }
    }
}
