//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICICI_Occupation_tbl
    {
        public int Id { get; set; }
        public string Occupation { get; set; }
        public string value { get; set; }
        public string Status { get; set; }
    }
}
