//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICICI_Country_tbl
    {
        public int Id { get; set; }
        public string Country_Name { get; set; }
        public string Value { get; set; }
        public string Status { get; set; }
    }
}
