//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Tbl
    {
        public int ID { get; set; }
        public string User_ID { get; set; }
        public string User_Password { get; set; }
        public string UserType { get; set; }
        public Nullable<int> islocked { get; set; }
        public Nullable<int> attemptcount { get; set; }
        public string Times { get; set; }
        public string Date { get; set; }
    }
}
