//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moter_RTO
    {
        public int Id { get; set; }
        public string RegisteredCityName { get; set; }
        public string RegisteredStateName { get; set; }
        public string RTOCode { get; set; }
        public string New { get; set; }
    }
}
