//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor_Insurance_Record
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Rto { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public string FualType { get; set; }
        public string RegistrationYear { get; set; }
        public string ClaimLastYear { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string CarVariant { get; set; }
        public string CarNumber { get; set; }
    }
}
