//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTO_MASTERS
    {
        public int RTO_ID { get; set; }
        public string RTO_CODE { get; set; }
        public string RTO_CITY { get; set; }
        public string RTO_STATE { get; set; }
        public string Zone { get; set; }
    }
}
