//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_store
    {
        public long SalesStore_M_ID { get; set; }
        public string Store_Code { get; set; }
        public string Store_Name { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string ManagerName { get; set; }
        public string Area { get; set; }
        public string Company_id { get; set; }
        public string Bank { get; set; }
        public string AccountNumber { get; set; }
        public string IFSC_Code { get; set; }
    }
}
