//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_category
    {
        public long Category_ID { get; set; }
        public string Category_Name { get; set; }
        public string CompanyCode { get; set; }
        public string Description { get; set; }
        public string ItemType { get; set; }
    }
}
