//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GetPremiumData
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Age { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Smoke { get; set; }
        public string Income { get; set; }
        public string Gender { get; set; }
        public string CustID { get; set; }
        public Nullable<decimal> SumInsurred { get; set; }
        public Nullable<int> Term { get; set; }
        public string frequency { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
