//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MakeType_Master
    {
        public int ID { get; set; }
        public string Make { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<bool> ISActive { get; set; }
    }
}
