//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IndiaFirst__CoverageOptions
    {
        public int ID { get; set; }
        public string Coverage_Options { get; set; }
        public Nullable<int> Max_M_Age { get; set; }
        public string Minimum_Sum_Assured { get; set; }
        public string Maximum_Sum_Assured { get; set; }
        public string Tag { get; set; }
    }
}
