//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GetPremiumRequestData
    {
        public int ID { get; set; }
        public string ADB { get; set; }
        public string ATPD { get; set; }
        public string CI { get; set; }
        public string HCB { get; set; }
        public string LAAge { get; set; }
        public string LADOB { get; set; }
        public string LAEmail { get; set; }
        public string LAFullName { get; set; }
        public string LAGender { get; set; }
        public string LANumber { get; set; }
        public string LAProposerSame { get; set; }
        public string LATobacco { get; set; }
        public string PEBased { get; set; }
        public string Term { get; set; }
        public string WOP { get; set; }
        public string additionalBenefit { get; set; }
        public string age { get; set; }
        public string betterHalfBenefit { get; set; }
        public string bond { get; set; }
        public string childAge { get; set; }
        public string childGender { get; set; }
        public string claimsOption { get; set; }
        public string cliDOB { get; set; }
        public string cliGender { get; set; }
        public string distributionChannel { get; set; }
        public string flexibleBenefitYear { get; set; }
        public string frequency { get; set; }
        public string fullName { get; set; }
        public string index { get; set; }
        public string investmentStrategy { get; set; }
        public string largeCap { get; set; }
        public string managed { get; set; }
        public string maturityAge { get; set; }
        public string maturityOption { get; set; }
        public string moneyMarket { get; set; }
        public string payoutMonths { get; set; }
        public string payoutOption { get; set; }
        public string payoutPercentageIncreasingIncome { get; set; }
        public string payoutPercentageLevelIncome { get; set; }
        public string payoutPercentageLumpsum { get; set; }
        public string pdf { get; set; }
        public string policyOption { get; set; }
        public string policyTerm { get; set; }
        public string postponement { get; set; }
        public string premiumPayingTerm { get; set; }
        public string product { get; set; }
        public string risingStar { get; set; }
        public string smoke { get; set; }
        public string spouseAge { get; set; }
        public string spouseDOB { get; set; }
        public string spouseFirstName { get; set; }
        public string spouseGender { get; set; }
        public string spouseLastName { get; set; }
        public string spouseTobaccoUser { get; set; }
        public string staff { get; set; }
        public string sumAssured { get; set; }
        public string top250 { get; set; }
        public string topUpBenefitPercentage { get; set; }
        public string tranId { get; set; }
        public string workSiteFlag { get; set; }
    }
}
