//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PinCode
    {
        public long Id { get; set; }
        public string PinCode { get; set; }
        public long CityId { get; set; }
        public Nullable<bool> IsInactive { get; set; }
        public string District { get; set; }
    }
}
