//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BajajResponce_Data
    {
        public int ID { get; set; }
        public string Contractid { get; set; }
        public string Quotrefno { get; set; }
        public string RefNO { get; set; }
        public string ScurityNo { get; set; }
        public string PolicyRef { get; set; }
        public Nullable<int> NetPremium { get; set; }
        public Nullable<int> Servicetaxamt { get; set; }
        public Nullable<int> edueAmt { get; set; }
        public Nullable<int> TotalPremium { get; set; }
        public Nullable<int> FinalPremium { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string taxCode { get; set; }
        public string TaxType { get; set; }
        public Nullable<int> AddTaxValue { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string PalnID { get; set; }
        public Nullable<int> IDData { get; set; }
        public string SumInsured { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Spouse { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string MemberCombo { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
