//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IPA_Occupation
    {
        public int ID { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> RISK_GRADE { get; set; }
        public string TTD_BENEFIT { get; set; }
        public string DECLINE_STATUS { get; set; }
        public Nullable<int> TAC_CODE { get; set; }
    }
}
