//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GetPremiumResponce
    {
        public int ID { get; set; }
        public string accidentalDeathPremium { get; set; }
        public string basePremium { get; set; }
        public string betterHalfPremium { get; set; }
        public string criticalIllnessPremium { get; set; }
        public string error { get; set; }
        public string hcbPremium { get; set; }
        public string pdfName { get; set; }
        public string permanentDisabilityPremium { get; set; }
        public string premium { get; set; }
        public string premiumWaiver { get; set; }
        public string sumAssured { get; set; }
        public string totalPremium { get; set; }
        public Nullable<int> Company { get; set; }
        public string PlanName { get; set; }
        public Nullable<int> CustID { get; set; }
        public string CoverAge { get; set; }
    }
}
