//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GodigitPakege
    {
        public int ID { get; set; }
        public string PakageCode { get; set; }
        public Nullable<int> Ageto { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public string PakageName { get; set; }
        public Nullable<int> Suminsured { get; set; }
    }
}
