//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public long City_ID { get; set; }
        public string City_Name { get; set; }
        public Nullable<long> State_ID { get; set; }
        public string CityCode { get; set; }
    }
}
