//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelationMaster
    {
        public long Id { get; set; }
        public Nullable<int> RelationCode { get; set; }
        public string Relation { get; set; }
        public string RelationType { get; set; }
        public Nullable<int> companyid { get; set; }
    }
}
