//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelPlan
    {
        public long ID { get; set; }
        public long PlanCode { get; set; }
        public string PlanName { get; set; }
        public decimal SumInsured { get; set; }
        public int SumInsuredCode { get; set; }
        public string Currency { get; set; }
        public Nullable<long> PlanID { get; set; }
    }
}
