//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravellerDetail
    {
        public long TravellerId { get; set; }
        public string TravellerName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public Nullable<bool> IsPassport { get; set; }
        public string PassportNo { get; set; }
        public string NomineeName { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public string Illness { get; set; }
        public string visaType { get; set; }
        public long FkSearchId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string searchType { get; set; }
    }
}
