//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInsuranceSearchBy
    {
        public long SearchId { get; set; }
        public string TravellerName { get; set; }
        public Nullable<int> age { get; set; }
        public string city { get; set; }
        public string contactno { get; set; }
        public string emailid { get; set; }
        public string destination { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> ageSpouse { get; set; }
        public Nullable<int> ageChild1 { get; set; }
        public Nullable<int> ageChild2 { get; set; }
        public Nullable<int> ageBrother { get; set; }
        public Nullable<int> ageMother { get; set; }
        public Nullable<int> ageFather { get; set; }
    }
}
