//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Insurance
    {
        public long Travel_id { get; set; }
        public Nullable<int> Age_From { get; set; }
        public Nullable<int> Age_To { get; set; }
        public string Plans { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public string CoverType { get; set; }
        public string TripType { get; set; }
        public Nullable<int> No_Of_Memebers { get; set; }
        public Nullable<int> TermFrom { get; set; }
        public Nullable<int> TermTo { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<long> Plan_ID { get; set; }
        public Nullable<long> PCode { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> destinationId { get; set; }
    }
}
