//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Two_Wheeler_Master
    {
        public long TwoWheeler_Insu_ID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Variance { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public string Rto_Location { get; set; }
        public string Email { get; set; }
    }
}
