//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HealthChartData
    {
        public string CompanyName { get; set; }
        public string LogoImage { get; set; }
        public int PremiumChartID { get; set; }
        public string PremiumDesc { get; set; }
        public Nullable<double> AgeFrom { get; set; }
        public string AgeFromDuration { get; set; }
        public Nullable<double> AgeTo { get; set; }
        public string AgeToDuration { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public string Premium { get; set; }
        public string Duration { get; set; }
        public string Type { get; set; }
        public Nullable<int> Individual { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Childrens { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string ProductName { get; set; }
        public string Floater { get; set; }
        public Nullable<decimal> BeforeServiceTax { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<int> suminsuredCode { get; set; }
    }
}
